# Generated by Django 4.1.5 on 2023-01-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='user_signed_count',
            field=models.IntegerField(default=0),
        ),
    ]
