# Generated by Django 4.1.5 on 2023-01-30 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meli_code',
            field=models.CharField(default=1111111111, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
